### PR TITLE
Added calibration options and sample sketch

### PR DESCRIPTION
**Pull request by storm2k15**
Added calibration functions to library:

bool Adafruit_BNO055::getCalibState(adafruit_bno055_calib_stat_t mask)
 Takes a adafruit_bno055_calib_stat_t mask and returns the related calibration state
 Returns true if calibrated
 Valid masks are:
    typedef enum
    { 
      /\* bit masks to read the CALIB_STAT register */
      CALIB_STAT_SYS                                           = 0xC0, //Overall system calibration state
      CALIB_STAT_GYR                                           = 0x30, //State for gyroscope
      CALIB_STAT_ACC                                           = 0x0C, //State for accelerometer
      CALIB_STAT_MAG                                           = 0x03 //State for magnetometer
    } adafruit_bno055_calib_stat_t; 

void Adafruit_BNO055::getCalibData(byte \* pbuffer)
 Takes a len=22 array of bytes and writes the currently active calibration into the array

void Adafruit_BNO055::setCalibData(byte \* pbuffer)
 Takes a len=22 array of bytes of calibration data and writes it into the sensor. This function must be
 called directly after .begin()

Added a calibration sample sketch to the library:
calibration.ino will allow any user to perform an easy calibration of his sensor to use in his own sketches.

### CODE REVIEW

**Comment by microbuilder** [comment]
Thanks for the pull request.  It looks like I can't merge this automatically, but I'll test the changes early next week and manually merge if necessary.

**Comment by storm2k15** [comment]
I think I did something wrong...;)

**Comment by microbuilder** [comment]
Normally, you'll want to start by 'pulling' from origin (getting the latest code from the parent repo into your local copy), and starting from the latest code before making your changes in the local repo.  Then 'commit' those changes to your personal repo (git add filename, ... git commit -m "Message"), and when you're done 'push' the change to your personal account on github (git push origin master). Then from github, with your personal copy of the repo updated, you can make a new pull request that can be merged automatically by us.  

It is a bit complicated, though.  We should really make a learning guide around creating git pull requests since it's a useful feature, but easy to make mistakes.

**Comment by storm2k15** [comment]
Yeah I noticed my pull shows all the other commits, too.

**Comment by storm2k15** [comment]
Guess you had no time to look into this yet?

**Comment by tdicola** [comment]
Oh I think this branch isn't what you want to submit changes to, instead look at the code on Adafruit's github account here: https://github.com/adafruit/Adafruit_BNO055  I actually just commited a function to read the calibration status that's similar to what your pull has too.  Going forward feel free to send pull requests to that Adafruit account repo.

**Pull request closed without merging**
